name: Release infrastructure to prod

on:
  release:
    types: [published]
    paths:
      - infrastructure/**

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Secrets to authorize terraform using the Azure Service Principal
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID_PROD }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET_PROD }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID_PROD}}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID_PROD }}
  # Additinal secrets and values to pass as variables to the infrastructure
  DB_PASSWORD: ${{ secrets.DB_PASSWORD_PROD }}
  DB_LOGIN: ${{ secrets.DB_LOGIN_PROD }}
  ENV: prod
  # A set of commands that will be ran prior to terraform init
  TERRAFORM_PRE_RUN: |
    # Install latest Azure CLI
    curl -skL https://aka.ms/InstallAzureCLIDeb | bash

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create terraform plan
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        id: plan_generator
        with:
          path: infrastructure
          label: ${{ env.ENV }}
          workspace: ${{ env.ENV }}
          variables: |
            db_password = "${{ env.DB_PASSWORD }}"
            db_login = "${{ env.DB_LOGIN }}"
          var_file: infrastructure/${{ env.ENV }}.tfvars.json

      - name: Upload plan artifact
        uses: actions/upload-artifact@v2
        with:
          name: plan
          path: ${{ steps.plan_generator.outputs.text_plan_path }}

  approve:
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - name: Download plan artifact
        uses: actions/download-artifact@v3
        with:
          name: plan
      - name: Read plan file
        id: read_plan_file
        uses: juliangruber/read-file-action@v1
        with:
          path: "plan.txt"
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.APPROVER_GITHUB_TOKEN }}
          approvers: pochmurnyGrzech
          minimum-approvals: 1
          issue-title: "Deploying a new version of infrastructure to the production"
          issue-body: "```${{ steps.read_plan_file.outputs.content }}```"
          exclude-workflow-initiator-as-approver: false

  apply:
    runs-on: ubuntu-latest
    needs: approve
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Apply approved plan
        uses: dflook/terraform-apply@v1
        with:
          path: infrastructure
          label: ${{ env.ENV }}
          workspace: ${{ env.ENV }}
          variables: |
            db_password = "${{ env.DB_PASSWORD }}"
            db_login = "${{ env.DB_LOGIN }}"
          var_file: infrastructure/${{ env.ENV }}.tfvars.json
          auto_approve: true
